apiVersion: v1
kind: Service
metadata:
  name: contosio-air
  namespace: dev
  labels:
    app.kubernetes.io/name: contosio-air
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: contosio-air
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000